Домашнее задание по lesson1

In [2]:
import torch
import time


In [3]:
# Задание 1.1 создание тензоров

t1 = torch.rand(3, 4)
t2 = torch.zeros(2, 3, 4)
t3 = torch.ones(5, 5)
t4 = torch.arange(16).reshape(4, 4)

print(t1)
print(t2)
print(t3)
print(t4)

tensor([[0.6427, 0.4488, 0.3010, 0.1226],
        [0.2852, 0.5667, 0.3372, 0.2947],
        [0.1423, 0.5067, 0.4028, 0.2936]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [4]:
# Задание 1.2 операции с тензорами

A = torch.randn(3, 4)
B = torch.randn(4, 3)

A_T = A.T
AB = torch.matmul(A, B)
B_T = B.T
elem = A * B_T
s = torch.sum(A)

print(A_T)
print(AB)
print(elem)
print(s)


tensor([[-1.3963,  1.4372,  0.1162],
        [ 1.5745,  0.2876,  1.0692],
        [-0.2930,  0.4366,  0.5755],
        [-0.0824, -0.1667, -0.5930]])
tensor([[-0.1648, -2.9796,  1.1576],
        [ 0.3499, -0.3230,  0.2926],
        [-0.1818, -0.5405,  1.3476]])
tensor([[-1.1259,  0.0071,  0.7800,  0.1740],
        [-0.5917, -0.5991,  0.6039,  0.2639],
        [ 0.0191,  0.5860, -0.6496,  1.3920]])
tensor(2.9655)


In [5]:
# Задание 1.3 индексация и срезы

X = torch.randn(5, 5, 5)

first_row = X[0]
last_col = X[:, :, -1]
center = X[2:4, 2:4, 2:4]
even = X[::2, ::2, ::2]

print(first_row)
print(last_col)
print(center)
print(even)

# Задание 1.4 формы

v = torch.arange(24)

print(v.reshape(2, 12))
print(v.reshape(3, 8))
print(v.reshape(4, 6))
print(v.reshape(2, 3, 4))
print(v.reshape(2, 2, 2, 3))

tensor([[ 0.6828, -1.2917,  0.8691, -1.8255,  1.9001],
        [ 1.7596,  1.7090,  0.0373,  0.8392, -1.8007],
        [-0.7838,  1.1711,  0.0528,  0.2460, -0.6056],
        [-0.2720, -0.9362,  1.3406, -1.1667, -1.5701],
        [ 1.0329, -0.8104,  1.3175,  0.4801, -0.2838]])
tensor([[ 1.9001, -1.8007, -0.6056, -1.5701, -0.2838],
        [-0.1262, -0.9747, -0.5044, -2.2178,  1.7845],
        [-1.3527, -0.7892,  0.0141,  1.0800,  0.6315],
        [-1.0042,  0.0793, -0.5309,  0.0644, -0.4225],
        [-0.8749, -0.7766,  0.5048,  0.7120,  0.0368]])
tensor([[[ 0.0845, -1.4013],
         [ 0.3336,  0.7711]],

        [[ 0.4944,  1.0042],
         [ 0.9714, -0.1683]]])
tensor([[[ 0.6828,  0.8691,  1.9001],
         [-0.7838,  0.0528, -0.6056],
         [ 1.0329,  1.3175, -0.2838]],

        [[ 0.5110, -1.1686, -1.3527],
         [ 1.1514,  0.0845,  0.0141],
         [ 2.5276,  0.4772,  0.6315]],

        [[ 0.4459, -0.6993, -0.8749],
         [-1.2382,  0.9882,  0.5048],
         [-1.0677,  

In [6]:

# Задание 2.1 автоград

x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
z = torch.tensor(4.0, requires_grad=True)

f = x**2 + y**2 + z**2 + 2*x*y*z
f.backward()

print(x.grad)
print(y.grad)
print(z.grad)


tensor(28.)
tensor(22.)
tensor(20.)


In [7]:
# Задание 2.2 mse

x = torch.randn(10)
y_true = torch.randn(10)

w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(0.1, requires_grad=True)

y_pred = w * x + b
mse = torch.mean((y_pred - y_true) ** 2)
mse.backward()

print(w.grad)
print(b.grad)

tensor(0.9132)
tensor(0.0907)


In [8]:
# Задание 2.3 цепное правило

x = torch.tensor(2.0, requires_grad=True)

f = torch.sin(x**2 + 1)
f.backward()

print(x.grad)

tensor(1.1346)


In [9]:
# Задание 3.1 данные

A = torch.randn(64, 1024, 1024)
B = torch.randn(128, 512, 512)
C = torch.randn(256, 256, 256)

# у меня cuda работает, но перестрахуемся
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [10]:
# Задание 3.2 измерение времени

def cpu_time(fn):
    start = time.time()
    fn()
    end = time.time()
    return (end - start) * 1000


def gpu_time(fn):
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)

    start.record()
    fn()
    end.record()

    torch.cuda.synchronize()
    return start.elapsed_time(end)

In [12]:
# Задание 3.3 сравнение операций

def test(x):

    cpu_matmul = cpu_time(lambda: torch.matmul(x, x))
    cpu_add = cpu_time(lambda: x + x)
    cpu_mul = cpu_time(lambda: x * x)
    cpu_t = cpu_time(lambda: x.T)
    cpu_sum = cpu_time(lambda: torch.sum(x))

    if torch.cuda.is_available():
        x_gpu = x.to("cuda")

        gpu_matmul = gpu_time(lambda: torch.matmul(x_gpu, x_gpu))
        gpu_add = gpu_time(lambda: x_gpu + x_gpu)
        gpu_mul = gpu_time(lambda: x_gpu * x_gpu)
        gpu_t = gpu_time(lambda: x_gpu.T)
        gpu_sum = gpu_time(lambda: torch.sum(x_gpu))
    else:
        gpu_matmul = None
        gpu_add = None
        gpu_mul = None
        gpu_t = None
        gpu_sum = None

    print("CPU:", cpu_matmul, cpu_add, cpu_mul, cpu_t, cpu_sum)
    print("GPU:", gpu_matmul, gpu_add, gpu_mul, gpu_t, gpu_sum)


test(A)
test(B)
test(C)

C:\Users\nelex\AppData\Local\Temp\ipykernel_34916\964725312.py:8: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4483.)
  cpu_t = cpu_time(lambda: x.T)


CPU: 173.97260665893555 14.000177383422852 12.000322341918945 0.9996891021728516 4.002809524536133
GPU: 54.470462799072266 5.5755839347839355 0.9656320214271545 0.0010239999974146485 1.110751986503601
CPU: 33.997297286987305 4.000663757324219 5.000829696655273 0.0 1.9991397857666016
GPU: 1.3999040126800537 0.4249599874019623 0.4382399916648865 0.0010239999974146485 0.2733759880065918
CPU: 9.000301361083984 2.000570297241211 1.9996166229248047 0.0 1.0020732879638672
GPU: 0.4484480023384094 0.20710399746894836 0.21913599967956543 0.002047999994829297 0.15491199493408203
